/** Authored Russian edition. Structural ids and routes follow the shared registry. */

import {
  pathways,
  windRoles,
  type PathwayDefinition,
  type PathwayId,
} from "./pathways";

const readerTextRu: Readonly<Record<string, string>> = {
  "For parents and responsible caregivers": "Родителям и взрослым, которые отвечают за ребёнка",
  "Keep the Sky Open": "Оставить небо открытым",
  "There is a child beside you, making something you cannot yet recognise. There is also a table that everyone needs for dinner. Both belong in this story.": "Рядом ребёнок делает что-то, чего вы пока не можете разглядеть. Есть ещё стол, который к ужину понадобится всем. В этой истории есть место и тому и другому.",
  "A Keeper of Conditions leaves room for surprise while holding the safety, care, and limits that belong to the adult.": "Хранитель условий оставляет место неожиданному, удерживая безопасность, заботу и границы, за которые отвечает взрослый.",
  "Sometimes the important change is in a sentence the adult was about to say.": "Иногда всё меняется в одной фразе, которую взрослый собирался произнести.",
  "What is already decided here, and what can the child still change?": "Что здесь уже решено — и что ребёнок ещё может изменить?",
  "The starting relation": "С чего начинаются отношения",
  "The child is not the project": "Ребёнок — не проект",
  "A child is a person in the room now, not the first draft of a future adult.": "Ребёнок — человек, который уже находится рядом, а не черновик будущего взрослого.",
  "Imagine a child drawing a house. Someone loves the red roof. The next house has a red roof too. After a while, the child looks up before choosing a colour.": "Представьте: ребёнок рисует дом. Кому-то очень нравится красная крыша. У следующего дома крыша тоже красная. Через некоторое время, прежде чем выбрать цвет, ребёнок поднимает глаза на взрослого.",
  "Praise can be warm and sincere. Yet the glance toward the adult may slowly take the place of looking at the picture. A Keeper notices that glance and makes room for a roof nobody has asked for.": "Похвала могла быть тёплой и искренней. Но взгляд на взрослого понемногу занимает место взгляда на рисунок. Хранитель замечает этот взгляд и оставляет место крыше, которой никто не заказывал.",
  "A productive asymmetry": "Неравенство, которое важно признать",
  "Equal dignity, unequal responsibility": "Равное достоинство, разная ответственность",
  "Parent and child have equal human worth; the adult still carries more power and duty.": "Человеческая ценность взрослого и ребёнка одинакова. Но власти, возможностей и обязанностей у взрослого больше.",
  "The adult holds safety, care, money, transport, permissions, and consequences the child cannot reasonably carry. Greater duty does not create ownership of the child's interests, pace, style, meaning, or future.": "Взрослый отвечает за безопасность, заботу, деньги, дорогу, разрешения и последствия, с которыми ребёнок пока не может справиться сам. Эта обязанность не даёт права владеть его интересами, темпом, стилем, смыслом или будущим.",
  "The adult holds the frame. The child can author a form inside it. When no choice exists, the adult names the requirement instead of disguising it as freedom.": "Взрослый удерживает рамку, ребёнок создаёт форму внутри неё. Если выбора нет, лучше прямо назвать требование, чем маскировать его под свободу.",
  "What a Keeper keeps": "Что именно хранит взрослый",
  "Conditions support many answers": "Условия не диктуют единственный ответ",
  "Good conditions do not guarantee a result; they make making, refusal, help, and rest more possible.": "Хорошие условия ничего не гарантируют. Они лишь дают больше места для попытки, отказа, просьбы о помощи и отдыха.",
  "A clear corner of the table, time to linger, someone who knows how to hold the scissors: the conditions are often ordinary things.": "Свободный угол стола, время повозиться, человек, который покажет, как держать ножницы: условия часто состоят из самых обыкновенных вещей.",
  "Safety": "Безопасность",
  "Name the hazard and act directly; reopen choice when it becomes real again.": "Назовите конкретную опасность и действуйте прямо. Верните выбор, когда он снова станет реальным.",
  "Time": "Время",
  "Protect unhurried time without turning every free hour into enrichment.": "Берегите неспешное время, не превращая каждый свободный час в развивающее занятие.",
  "Rest and energy": "Отдых и силы",
  "Treat tiredness as information, not a verdict. Rest belongs to Ground.": "Считайте усталость информацией, а не приговором. Отдых принадлежит Земле.",
  "Materials and access": "Материалы и доступ",
  "Make access real without implying that more supplies must produce more creativity.": "Дайте реальный доступ, но не внушайте, будто больше материалов обязаны дать больше творчества.",
  "Craft and instruction": "Ремесло и обучение",
  "Teach the safe or useful map, then return destination and whole action to the maker.": "Покажите безопасную или полезную карту, а затем верните автору пункт назначения и действие целиком.",
  "Boundaries": "Границы",
  "State limits around cost, noise, privacy, consent, and shared belongings plainly.": "Прямо назовите границы цены, шума, приватности, согласия и общих вещей.",
  "Conversation": "Разговор",
  "Make questions and help available without demanding explanation or commentary.": "Оставьте доступными вопросы и помощь, не требуя объяснений или комментариев.",
  "Consequences and Return": "Последствия и Возвращение",
  "Return borrowed things, mend what was damaged, listen to an answer. A drawing can also stay in its drawer.": "Вернуть чужие вещи, починить сломанное, услышать ответ. Рисунок при этом может остаться в ящике.",
  "Before choosing a tone": "Прежде чем выбирать тон",
  "Name the mode honestly": "Честно назвать режим",
  "Gentle wording does not make an instruction into an invitation, and a question is not open if only yes can survive.": "Мягкие слова не превращают требование в приглашение. Вопрос нельзя назвать открытым, если приемлем только ответ «да».",
  "Choose the mode that matches the adult's real responsibility and the amount of choice actually available.": "Форма разговора должна соответствовать реальной ответственности взрослого и тому выбору, который действительно доступен.",
  "Direct instruction": "Прямое требование",
  "Use for immediate safety, care, law, or an unavoidable responsibility. Explain afterward and restore choice where possible.": "Подходит для немедленной безопасности, заботы, закона или неизбежной обязанности. Объясните позже и верните выбор там, где он возможен.",
  "Boundary with choice": "Граница с выбором",
  "Name the fixed obligation and offer only workable ways to meet it.": "Назовите неизменную обязанность и предложите только те способы её выполнить, которые действительно доступны.",
  "Genuine invitation": "Настоящее приглашение",
  "Use only when refusal will not cost affection, status, or future access.": "Используйте его лишь тогда, когда отказ не лишит ребёнка любви, положения или будущего доступа.",
  "Co-exploration": "Совместное исследование",
  "Learn together while the adult continues to hold adult risk and responsibility.": "Исследуйте вместе, но риск и взрослую ответственность продолжает нести взрослый.",
  "Witnessing and stepping back": "Быть свидетелем и отступить",
  "Stay available without adding another suggestion or abandoning the conditions.": "Оставайтесь рядом, не добавляя ещё один совет и не бросая условия без поддержки.",
  "One small family Flight": "Один небольшой семейный Полёт",
  "The bridge bends": "Мост прогнулся",
  "Making begins to move when the material answers back.": "Дело оживает, когда материал отвечает.",
  "Imagine a paper bridge between two cups. A toy car reaches the middle and the road sags. The adult reaches for thicker card. The child folds the fallen sheet like a fan and tries again.": "Представьте бумажный мост между двумя чашками. Машинка доезжает до середины, и дорога прогибается. Взрослый тянется за картоном потолще. Ребёнок складывает упавший лист гармошкой и пробует снова.",
  "This time the car crosses. Then another goes on, and both fall into the river below. Someone laughs. The bridge gets a new fold; the river gets a name. Later, the cups go back to the kitchen.": "На этот раз машинка проезжает. Следом на мост въезжает ещё одна — и обе падают в реку внизу. Кто-то смеётся. У моста появляется новый сгиб, у реки — имя. Потом чашки возвращаются на кухню.",
  "No altitude score": "Без оценки высоты",
  "Before the next suggestion": "Прежде чем подсказать",
  "The maker may still be listening to what the work has done.": "Автор, возможно, ещё прислушивается к тому, что получилось.",
  "A child leaves a drawing on the table. You can see a way to improve it. Before speaking, there is time to look: where the line grew darker, what was rubbed out, which part the child returns to. Ask whether they want to tell you about it.": "Ребёнок оставляет рисунок на столе. Вы видите, что можно улучшить. Прежде чем заговорить, есть время рассмотреть: где линия стала темнее, что стёрто, к какой части ребёнок возвращается. Можно спросить, хочет ли он об этом рассказать.",
  "If they want to finish, the drawing can be finished. Returning borrowed pens or making space for dinner is a separate responsibility.": "Если он хочет закончить, рисунок может остаться таким. Вернуть чужие фломастеры или освободить место к ужину — отдельная обязанность.",
  "AI in the family": "ИИ в семье",
  "Wind, not wings or pilot": "Ветер, но не крылья и не пилот",
  "AI may support a bounded operation; it does not judge the child, choose a worthy future, or absorb responsibility.": "ИИ может помочь в ограниченной задаче. Он не оценивает ребёнка, не выбирает для него достойное будущее и не забирает ответственность взрослого.",
  "A child asks for three possible names for a creature, then invents a fourth from two of them. The parent helps with the tool and protects private information. The story can keep growing in the child’s voice, with or without the screen.": "Ребёнок просит три имени для придуманного существа, а потом собирает из двух четвёртое. Взрослый помогает с инструментом и бережёт личные данные. История продолжает расти голосом ребёнка — с экраном или без него.",
  "Repair, not parental shame": "Исправление вместо родительского стыда",
  "When care becomes Gravity": "Когда забота превращается в Инерцию",
  "Gravity appears when one route becomes unquestioned destiny; every family can notice and repair it.": "Инерция начинается там, где один путь перестают обсуждать и объявляют судьбой. Это случается в любой семье — и это можно заметить и поправить.",
  "The aim is not perfect parenting. It is to make responsibility visible and repair the next part that can be repaired.": "Задача не в безупречном родительстве. Достаточно увидеть, кому принадлежит ответственность, и исправить ближайшее из того, что ещё можно исправить.",
  "The hidden brief": "Скрытое техническое задание",
  "Make anything secretly means make my answer.": "Фраза «сделай что угодно» на деле означает «сделай мой вариант».",
  "Name the constraint; call a required form instruction and accept surprise when it is truly open.": "Назовите ограничение. Обязательную форму честно назовите требованием, а там, где выбор открыт, примите неожиданный ответ.",
  "Safety covers every uncertainty": "Безопасностью называют любую неопределённость",
  "Mess, failure, judgment, or wasted money is renamed danger.": "Беспорядок, неудачу, чужую оценку или напрасные траты переименовывают в опасность.",
  "Name the concrete risk, hold that boundary, and reopen choices outside it.": "Назовите конкретный риск, удержите эту границу и верните выбор за её пределами.",
  "The absent Keeper": "Исчезнувший хранитель",
  "It is your choice transfers adult burdens to the child.": "Фраза «это твой выбор» перекладывает взрослую ношу на ребёнка.",
  "Take back adult responsibility for risk, cost, time, cleanup, and consequences.": "Верните взрослому ответственность за риск, цену, время, уборку и последствия.",
  "Explanation interrupts action": "Объяснение прерывает действие",
  "Questions and corrections arrive before the child can complete a movement.": "Вопросы и поправки появляются раньше, чем ребёнок успевает завершить движение.",
  "Ask when input is wanted; offer one relevant technique and return to the whole.": "Спросите, когда нужен ваш отклик. Предложите один уместный приём и вернитесь к целому.",
  "What Grounds Flight?": "На чём держится Полёт?",
  "Separate a recurring conflict into visible facts, adult responsibility, possible Gravity, a fixed frame, and an open part.": "Разберите повторяющийся конфликт: что произошло, за что отвечает взрослый, где включилась Инерция, что в рамке неизменно, а что по-настоящему открыто.",
  "Write one next-time sentence naming what the adult must hold and what the child can truly author.": "Сформулируйте одну фразу на следующий раз: что обязан удержать взрослый и что ребёнок действительно может решить сам.",
  "You can name what is fixed and what remains open, or the part you still need to discuss.": "Стало понятнее, что обязательно, где остаётся выбор и о чём ещё нужно поговорить.",
  "Use after the moment, never instead of immediate safety action; the result is not a family diagnosis or score.": "Возвращайтесь к этому после события, а не вместо срочного действия ради безопасности. Это не диагноз семье и не оценка.",
  "What I must hold…": "Что обязан удержать я…",
  "What the child can truly author…": "Что ребёнок действительно может решить сам…",
  "Instruction or Invitation?": "Требование или приглашение?",
  "Test one familiar sentence against what is required, why it is required, what is open, and whether no can survive.": "Проверьте привычную фразу: что здесь обязательно, почему, что остаётся открытым и можно ли на самом деле ответить «нет».",
  "Rewrite the sentence in the honest mode and name the behaviour that will make the openness real.": "Перепишите фразу честно и назовите действие взрослого, благодаря которому выбор останется реальным.",
  "The words and the actual distribution of choice agree.": "Слова совпадают с тем, как в действительности распределён выбор.",
  "Do not soften an unavoidable instruction into manipulation or weaken a necessary safety boundary.": "Не маскируйте неизбежное требование мягкими словами и не ослабляйте необходимую границу безопасности.",
  "What is required?": "Что обязательно?",
  "Why?": "Почему?",
  "What is genuinely open?": "Где выбор настоящий?",
  "Can no survive?": "Можно ли здесь ответить «нет»?",
  "Ground Landing": "Приземление",
  "Close, pause, care, repair, ask for help, or rest at the end of a family attempt.": "В конце семейной попытки можно закрыть её, поставить на паузу, позаботиться о последствиях, что-то исправить, попросить помощи или отдохнуть.",
  "Name only what should be put away, returned, cleaned, kept safely, repaired, helped, or left undecided.": "Назовите только то, что нужно убрать, вернуть, очистить, сохранить, исправить, кому помочь и что пока оставить нерешённым.",
  "The present cycle no longer demands hidden attention.": "Этот цикл больше не удерживает фоновое внимание.",
  "Close with no next project required; rest is not a productivity technique.": "После закрытия не обязан появляться следующий проект. Отдых — не приём для повышения продуктивности.",
  "Starting a home project": "Домашний проект",
  "“Make anything,” says the adult, pausing a video beside the materials. The child makes the roof crooked. A hand reaches over to straighten it.": "«Делай что хочешь», — говорит взрослый и ставит видео на паузу рядом с материалами. Ребёнок делает кривую крышу. Рука взрослого тянется её выровнять.",
  "Say make anything while requiring the example from a video.": "Сказать «делай что хочешь», но на деле ждать точной копии примера из видео.",
  "The hand can stop. “I was expecting the one in the video. What are you making?” The child may turn the screen away. The table still needs to be clear in forty minutes.": "Рука может остановиться. «Я ждал, что будет как на видео. А что ты делаешь?» Ребёнок, может быть, отвернёт экран. Через сорок минут стол всё равно понадобится освободить.",
  "The material and boundary are real; the example remains a map, not the hidden answer.": "Материал и граница реальны; пример остаётся картой, а не спрятанным правильным ответом.",
  "A tool becomes unsafe": "Инструмент стал опасным",
  "A fastening has come loose and the tool can hurt someone.": "Крепление разболталось, и инструмент может кого-то ранить.",
  "Use a false invitation while expecting immediate compliance.": "Сделать вид, будто это приглашение, хотя требуется немедленно остановиться.",
  "Stop the action directly, make the tool safe, then reopen continue, demonstration, another tool, or ending.": "Прямо остановить действие и привести инструмент в безопасное состояние. После этого снова открыть выбор: продолжить, посмотреть показ, взять другой инструмент или закончить.",
  "The adult owns the safety duty; choice returns when it becomes real.": "За безопасность отвечает взрослый. Выбор возвращается, когда снова становится настоящим.",
  "A fort occupies shared space": "Крепость заняла общее пространство",
  "A blanket fort reaches across the doorway. Someone carrying dinner cannot get through. From inside comes a voice: “But that is the sea.”": "Крепость из одеял добралась до дверного проёма. Человек с ужином не может пройти. Изнутри доносится: «Но там же море».",
  "Let the creative project erase consent and shared access.": "Позволить творческому проекту отменить согласие и общий доступ.",
  "The passage has to open. The adult names that limit and waits. Perhaps the sea acquires a ferry, perhaps the fort moves, perhaps the building ends for today. Other people still need their way through.": "Проход нужно открыть. Взрослый называет эту границу и ждёт. Может быть, у моря появится паром, крепость переедет или стройка на сегодня закончится. Другим людям по-прежнему нужен проход.",
  "Authorship does not cancel consent.": "Авторство не отменяет согласие.",
  "The parent has no Lift": "У родителя сегодня нет сил",
  "The adult lacks enough attention or energy for the planned activity.": "У взрослого не хватает внимания или энергии на запланированное занятие.",
  "Push through to perform availability and become unsafe or resentful.": "Заставить себя участвовать, изображая доступность, а в итоге стать раздражённым или невнимательным к безопасности.",
  "Name the limit and offer a smaller paper version, preparation, help, another time, or stopping.": "Назвать предел и предложить уменьшенную бумажную версию, только подготовку, помощь, другое время или остановку.",
  "The parent is part of the conditions; low Lift changes the attempt, not anyone's worth.": "Родитель тоже часть условий. Недостаток сил меняет попытку, но не ценность кого-либо.",
  "Sharing the result": "Поделиться результатом",
  "A parent wants to show, post, or narrate a child's form.": "Родитель хочет показать, опубликовать или пересказать сделанное ребёнком.",
  "Treat public praise as proof that the activity mattered.": "Считать публичную похвалу доказательством, что занятие имело смысл.",
  "Offer privacy, one person, a specific question, or wider sharing; do not post without agreement.": "Предложить варианты: оставить личным, показать одному человеку, задать конкретный вопрос или поделиться шире. Не публиковать без согласия.",
  "Return can be real without compulsory publicity; actual effects still receive care.": "Возвращение возможно и без обязательной публичности. Реальные последствия всё равно требуют внимания.",
  "The adult holds safety, care, privacy, and consequences the child cannot carry. Emergencies and unavoidable duties are named directly.": "Взрослый отвечает за безопасность, заботу, приватность и последствия, которые ребёнок не может нести сам. Опасность и неизбежные обязанности называют прямо.",
  "A real invitation allows refusal without withdrawing affection. Sharing a child’s work requires their agreement; AI must not be used to profile or rank them.": "Настоящее приглашение допускает отказ без потери любви. Чтобы поделиться работой ребёнка, нужно его согласие; ИИ нельзя использовать для составления его профиля или рейтинга.",
  "When a family needs medical, psychological, educational, legal, or social help, the metaphor gives way to concrete care.": "Когда семье нужна медицинская, психологическая, образовательная, юридическая или социальная помощь, метафора уступает место конкретной заботе.",
  "Keep a place at the table for the child who is here now.": "Оставлять за столом место ребёнку, который рядом сейчас.",
  "When care turns into control, notice it, repair what you can, and make room again.": "Когда забота становится контролем — замечать это, исправлять возможное и снова освобождать место.",
  "Rewrite one real adult sentence in its honest mode.": "Перепишите одну настоящую фразу взрослого в честном режиме.",
  "Separate adult responsibility from a hidden expected result.": "Отделите ответственность взрослого от скрытого ожидаемого результата.",
  "Creative Climate Map": "Карта творческого климата",
  "Inspect conditions for one attempt without profiling a child or family.": "Посмотрите на условия одной попытки, не составляя профиль ребёнка или семьи.",
  "Close or pause without a required next project.": "Закройте или приостановите цикл без обязательного следующего проекта.",
  "Set the Wind": "Настроить Ветер",
  "Set a human-first family boundary around AI.": "Установите семейную границу вокруг ИИ, оставив человека первым.",
  "Remembering Flight": "Вспомнить Полёт",
  "Apply the same philosophy to your own present life.": "Примените ту же философию к собственной нынешней жизни.",
  "The Return": "Возвращение",
  "Read the article on consequence, repair, privacy, and honest endings.": "Прочитайте статью о последствиях, исправлении, приватности и честных завершениях.",
  "Read the Manifesto": "Читать манифест",
  "See the full worldview behind the parent path.": "Посмотрите на целостное мировоззрение, из которого вырос родительский путь.",
  "For adults beginning from the life already here": "Взрослым, которые начинают с той жизни, что уже есть",
  "An unfinished question can travel quietly through years of work, meals, errands, and sleep. One day something ordinary brings it back within reach.": "Незавершённый вопрос может годами жить среди работы, ужинов, поездок и сна. Однажды что-то обыкновенное снова делает его слышным.",
  "The life you have gives this question its material: experience, people, limits, and whatever time can be found.": "Вопросу предстоит встретиться с тем, что уже есть: опытом, людьми, пределами и временем, которое удаётся найти.",
  "The first opening may be smaller than the change you once imagined.": "Первое открывшееся место может быть меньше перемены, которую вы когда-то представляли.",
  "A page, a conversation, a repaired object. Something close enough to begin with.": "Страница, разговор, починенная вещь. Что-то достаточно близкое, чтобы начать.",
  "An old question": "Старый вопрос",
  "Flight is an event, not a kind of person": "Полёт — событие, а не тип человека",
  "A long season on Ground can hold more than anyone sees.": "Долгое время на Земле может вмещать больше, чем видно со стороны.",
  "Imagine finding an old notebook while looking for a receipt. Half a page of a story; a sentence crossed out twice. You remember the room in which you wrote it before you remember what the story was about.": "Представьте: вы ищете чек и находите старую тетрадь. Полстраницы рассказа, дважды зачёркнутое предложение. Сначала вспоминается комната, в которой вы писали, и только потом — о чём был рассказ.",
  "The notebook can stay open beside tonight’s bills. Neither page has to explain away the other.": "Тетрадь может остаться открытой рядом с сегодняшними счетами. Одной странице не нужно оправдываться перед другой.",
  "A direction is enough": "Направления достаточно",
  "Purpose is a practice, not a hidden assignment": "Смысл — практика, а не спрятанное задание",
  "Purpose is a way of meeting what is unfinished, not one mission buried inside you.": "Смысл проявляется в том, как человек встречает незавершённое. Это не единственная миссия, спрятанная где-то внутри.",
  "An old question may return in a different shape. The story you wanted to publish becomes a letter to one person. A wish to build something becomes a shelf that finally fits an awkward corner. The answer can matter at this size.": "Старый вопрос может вернуться в другом виде. Рассказ, который хотелось опубликовать, становится письмом одному человеку. Желание что-то построить — полкой, которая наконец помещается в неудобный угол. Ответ может иметь значение и в таком масштабе.",
  "Some questions stay with us for decades. Others finish their work in one afternoon.": "Одни вопросы остаются с нами на десятилетия. Другие успевают сделать своё дело за один день.",
  "The available material": "Материал, который уже есть",
  "Begin from the life you already have": "Начать с собственной жизни",
  "The present body, ties, skills, obligations, and energy are the starting material, not an obstacle to real life.": "Нынешнее тело, отношения, навыки, обязательства и запас сил — исходный материал, а не помеха «настоящей» жизни.",
  "This does not make every commitment sacred. It means seeing what is real clearly enough to choose within it, negotiate, ask for help, or responsibly change it.": "Это не делает священным каждое обязательство. Речь о том, чтобы достаточно ясно увидеть реальность: выбрать внутри неё, договориться, попросить помощи или ответственно что-то изменить.",
  "Maintenance, care, administration, recovery, and sleep are part of Ground. They need no poetic title to deserve respect.": "Быт, забота, организационные дела, восстановление и сон принадлежат Земле. Им не нужно красивое название, чтобы заслуживать уважения.",
  "Two different pulls": "Две разные силы",
  "Ground is not Gravity": "Земля — не Инерция",
  "Ground is the reality that supports and limits an attempt; Gravity is an unexamined route hardened into destiny.": "Земля — это реальность, которая поддерживает попытку и задаёт ей пределы. Инерция — путь, который давно не проверяли и успели принять за судьбу.",
  "Money, care, craft, work, AI, and rest can each be honest conditions. They become Gravity language when one response is made morally compulsory and alternatives can no longer be discussed.": "Деньги, забота, ремесло, работа, ИИ и отдых могут быть честными условиями. Они становятся языком Инерции, когда один ответ объявляют морально обязательным, а альтернативы перестают обсуждать.",
  "Some doors are materially locked. The honest movement may be to name the door, find company, seek qualified help, or stop calling it a personal failure.": "Некоторые двери действительно закрыты. Иногда честный шаг — назвать такую дверь, найти союзников или профессиональную помощь и перестать считать её личным поражением.",
  "Money": "Деньги",
  "Reliable income may be necessary now.": "Стабильный доход может быть необходим прямо сейчас.",
  "Gravity says serious adults may make only what has a market.": "Инерция говорит: серьёзный взрослый может создавать только то, что продаётся.",
  "Care": "Забота",
  "Choices affect people who depend on us.": "Наш выбор затрагивает людей, которые от нас зависят.",
  "Gravity says care erases every question of one's own.": "Инерция говорит: забота стирает любые собственные вопросы.",
  "Craft": "Ремесло",
  "A form may require repetition and skills not yet learned.": "Форма может потребовать повторения и навыков, которым ещё предстоит научиться.",
  "Gravity says not being exceptional immediately proves the question was false.": "Инерция говорит: если сразу не получилось выдающегося результата, вопрос был ложным.",
  "Work": "Работа",
  "Some tasks belong to an accepted or currently unavoidable agreement.": "Некоторые задачи входят в принятое или пока неизбежное соглашение.",
  "Gravity says a role is the whole truth about what one may want.": "Инерция говорит: рабочая роль полностью определяет, чего человеку позволено хотеть.",
  "AI": "ИИ",
  "A tool can make some versions faster.": "Инструмент может ускорить создание некоторых версий.",
  "Gravity says machine capability makes human attention and judgment worthless.": "Инерция говорит: возможности машины обесценивают человеческое внимание и суждение.",
  "Rest": "Отдых",
  "Capacity can be low and recovery necessary.": "Сил может быть мало, а восстановление — необходимо.",
  "Gravity says rest must be earned by future output.": "Инерция говорит: отдых нужно заслужить будущим результатом.",
  "Guidance without surrender": "Подсказка без капитуляции",
  "Maps, scaffolds, and authored direction": "Карты, временные опоры и собственное направление",
  "Outside knowledge can protect and teach; authorship does not require purity from influence.": "Чужое знание может учить и защищать. Авторству не нужна стерильность от влияния.",
  "A teacher’s way of holding a tool may still serve you well. A sentence about what “people like us” should want may no longer fit. They can be examined separately. Gratitude leaves room for disagreement.": "Способ держать инструмент, которому научил учитель, по-прежнему помогает. Фраза о том, чего должны хотеть «такие, как мы», возможно, уже не подходит. Их можно рассмотреть по отдельности. Благодарность оставляет место несогласию.",
  "A revisable arc": "Дуга, которую можно пересмотреть",
  "Call → Compass → Lift → Making → Flight → Return → Ground": "Зов → Компас → Подъём → Дело → Полёт → Возвращение → Земля",
  "A question takes shape, meets the world, and comes back changed.": "Вопрос обретает форму, встречается с миром и возвращается изменившимся.",
  "Call draws attention. Compass finds a direction among real limits and other lives. Lift is the support that makes a beginning possible. Making gives the answer a body; Flight lets it meet something beyond intention. Return receives what happened. Ground holds what comes after.": "Зов привлекает внимание. Компас помогает выбрать направление среди реальных границ и чужих жизней. Подъём — опоры и силы, с которыми можно начать. Дело даёт ответу тело; Полёт выпускает его за пределы намерения. Возвращение принимает случившееся. Земля удерживает то, что будет дальше.",
  "The path can turn back, wait, or end. Its shape is easier to see after the encounter.": "Путь может повернуть назад, подождать или закончиться. Его очертания часто становятся видны уже после встречи.",
  "Intention meets resistance": "Намерение встречает сопротивление",
  "Craft, error, repetition, and boredom belong": "Ремесло, ошибка, повторение и скука тоже здесь",
  "Learning how material behaves does not make imagination less free.": "Знание материала не делает воображение менее свободным.",
  "A line wobbles. A joint will not fit. You try again, adjusting the pressure, and suddenly your hand understands something the instructions could only describe. For a moment, the work holds your whole attention.": "Линия дрожит. Детали не сходятся. Вы пробуете ещё раз, чуть меняете нажим — и вдруг рука понимает то, что инструкция могла только описать. На мгновение работа забирает всё внимание.",
  "Repetition can bring that pleasure. It can also tire you. Boredom is not proof that a route is wrong; difficulty is not proof that it is right.": "Повторение может принести это удовольствие. Может и утомить. Скука не доказывает, что путь неверен; трудность не доказывает обратного.",
  "Problem Finder": "Найти вопрос",
  "Turn one noticed mismatch into a possible question—or an honest refusal.": "Превратите одно замеченное несоответствие в возможный вопрос — или честно откажитесь отвечать на него.",
  "10 minutes": "10 минут",
  "Finish: I notice…, I care because…, A possible question is…. Then answer yes, no, not now, or differently.": "Закончите три фразы: «Я замечаю…», «Мне это важно, потому что…», «Возможный вопрос…». Затем ответьте: да, нет, не сейчас или иначе.",
  "The mismatch becomes one possible question or a complete non-answer.": "Несоответствие стало одним возможным вопросом — или получило полноценный ответ «нет».",
  "Pain, fear, and irritation are not automatically Calls. Safety, rest, or help may come first.": "Боль, страх и раздражение не обязаны становиться Зовом. Сначала могут понадобиться безопасность, отдых или помощь.",
  "One-Day Form": "Форма на один день",
  "Give one question a small form that reality can answer.": "Придайте одному вопросу небольшую форму, на которую реальность сможет ответить.",
  "20–60 minutes; never more than one day": "20–60 минут, но не больше одного дня",
  "Choose a note, sketch, repair, request, conversation, arrangement, boundary, small test, or decision; define the stop point first.": "Выберите заметку, набросок, исправление, просьбу, разговор, перестановку, границу, небольшую проверку или решение. Сначала определите точку остановки.",
  "Someone can read it, use it, try it, or answer it.": "Это уже можно прочитать, попробовать, использовать или встретить ответом.",
  "This is not a compulsory first instalment of a large project.": "Это не обязательный первый взнос в большой проект.",
  "The Boring Hinge": "Скучный шарнир",
  "Practise the small craft operation on which a larger action turns.": "Потренируйте небольшую ремесленную операцию, на которой держится более крупное действие.",
  "15 minutes": "15 минут",
  "Practise one hinge slowly, then perform or view the whole action once and keep only what helps it.": "Медленно отработайте один шарнир, затем один раз выполните или посмотрите действие целиком и оставьте только то, что ему помогает.",
  "Technique has returned to the living form.": "Техника снова служит живой форме.",
  "Mastery is not a moral rank, and exhaustion is not disciplined practice.": "Мастерство — не моральный ранг, а истощение — не признак дисциплины.",
  "Relationship and Obligation Check": "Проверка отношений и обязательств",
  "Make freedom and responsibility visible before a consequential change.": "До важного изменения сделайте видимыми свободу и ответственность.",
  "List affected people, real promises and dependencies, needed consent, negotiable parts, and what remains yours; plan one conversation or reduce the stakes.": "Перечислите затронутых людей, реальные обещания и зависимости, необходимое согласие, предметы для переговоров и то, что остаётся вашим. Запланируйте один разговор или снизьте ставки.",
  "The experiment is responsibly bounded or deliberately paused.": "Эксперимент получил ответственную границу или намеренно поставлен на паузу.",
  "Do not call every tie Gravity or every constraint sacred Ground; seek outside help when power makes conversation dangerous.": "Не называйте всякую связь Инерцией, а всякое ограничение — священной Землёй. Если неравенство власти делает разговор опасным, ищите внешнюю помощь.",
  "Honorable Refusal": "Честный отказ",
  "Give no, not now, or differently a real form.": "Придайте ответу «нет», «не сейчас» или «иначе» настоящую форму.",
  "5–20 minutes": "5–20 минут",
  "Complete: I will not answer this Call now because…. Communicate, offer another form, name a reconsideration condition, or close privately as needed.": "Закончите фразу: «Я не отвечу на этот Зов сейчас, потому что…». Если нужно, сообщите решение, предложите другую форму, назовите условие пересмотра или закройте вопрос для себя.",
  "The people who need to know have heard your answer.": "Те, кому нужно знать о вашем решении, услышали ответ.",
  "Refusal does not erase unavoidable obligations or their effects.": "Отказ не стирает неизбежные обязательства и их последствия.",
  "Too many Calls": "Слишком много Зовов",
  "Many lively ideas together prevent any one of them from meeting reality.": "Множество живых идей одновременно не даёт ни одной встретиться с реальностью.",
  "Write the ideas where you can return to them. One may fit the time and commitments you have now. Choosing it leaves the others on the page.": "Запишите идеи там, куда можно вернуться. Одна из них, возможно, помещается в нынешнее время и обязательства. Когда вы выбираете её, остальные остаются на странице.",
  "Unchosen ideas are not failed destinies; the aim is one authored encounter or honest Ground.": "Невыбранные идеи — не проваленные судьбы. Достаточно одной авторской встречи или честной Земли.",
  "The tired adult": "Уставший взрослый",
  "A wanted question appears after work and care when the adult can barely stay awake.": "Желанный вопрос появляется после работы и заботы, когда человек едва держится на ногах.",
  "Call exhaustion fear, prescribe discipline as proof of desire, or allow rest only as fuel for output.": "Назвать истощение страхом, требовать дисциплины как доказательства желания или разрешить отдых только как топливо для результата.",
  "The notebook is open, but the same sentence has been read three times. Close it and leave a scrap of paper at the line. Eat, sleep, ask for help if you need it. The scrap can keep the place.": "Тетрадь открыта, но одно предложение прочитано уже три раза. Можно закрыть её, оставив на нужной строке обрывок бумаги. Поесть, поспать, попросить помощи, если она нужна. Место сохранит закладка.",
  "Rest belongs to this life, whether the notebook opens tomorrow or much later.": "Отдых принадлежит этой жизни, откроется ли тетрадь завтра или гораздо позже.",
  "AI proposes the destination": "ИИ предлагает пункт назначения",
  "AI returns a polished, plausible public project that was not the adult's question before the prompt.": "ИИ выдаёт гладкий и правдоподобный публичный проект, которого не было в исходном вопросе человека.",
  "Treat fluency or predicted demand as purpose, or defend humanity only by claiming the machine is worse.": "Принять гладкость или предсказанный спрос за цель — либо защищать человека лишь утверждением, что машина делает хуже.",
  "Name the proposal as a Wind-shaped map, recover the prior observation, ask whose question it is, then reject, keep as reference, or deliberately transform one part.": "Назвать предложение картой, созданной Ветром, вернуться к исходному наблюдению и спросить, чей это вопрос. Затем отвергнуть, оставить как справку или осознанно преобразовать одну часть.",
  "Direction, adoption, affected relationships, and Return remain human whether AI is used or refused.": "Направление, принятие, затронутые отношения и Возвращение остаются человеческими — с ИИ или без него.",
  "Thirty invitations": "Тридцать приглашений",
  "A page to wander through. A question may stay with you after the book is closed.": "Страница, по которой можно побродить. Какой-то вопрос, возможно, останется с вами и после закрытия книги.",
  "Read in any order; there is nothing to complete.": "Читайте в любом порядке; заканчивать весь список не требуется.",
  "Notice": "Замечать",
  "Which small inconvenience have you stopped noticing?": "Какое маленькое неудобство вы перестали замечать?",
  "What do you care for that has never appeared on a list of ambitions?": "О чём вы заботитесь, хотя этого никогда не было в списке ваших стремлений?",
  "What would you still want to make if nobody knew who made it?": "Что хотелось бы сделать, если бы никто не узнал имени автора?",
  "Whose voice do you hear in “someone like me should…”?": "Чей голос слышен во фразе «такой человек, как я, должен…»?",
  "What is quietly holding up your day?": "Что незаметно удерживает ваш день?",
  "What catches your eye when you have nowhere to hurry?": "За что цепляется взгляд, когда некуда спешить?",
  "Choose": "Выбирать",
  "Which question has returned more than once?": "Какой вопрос возвращался уже несколько раз?",
  "What makes it matter at this moment?": "Почему он важен именно сейчас?",
  "Who else would live with the answer?": "Кому ещё предстоит жить с ответом?",
  "What must remain safe while you try?": "Что должно остаться в безопасности, пока вы пробуете?",
  "What discovery would make you change direction?": "Какое открытие заставило бы вас изменить направление?",
  "Which old instruction still helps your hands?": "Какое старое наставление до сих пор помогает рукам?",
  "Give form": "Придавать форму",
  "What is within reach today: a whole afternoon, ten minutes, another person?": "Что доступно сегодня: целый день, десять минут, другой человек?",
  "Which part could become possible with help?": "Какая часть стала бы возможной с чьей-то помощью?",
  "How small could this idea become and still interest you?": "Насколько маленькой может стать эта идея, чтобы всё ещё быть вам интересной?",
  "What could you put on the table for a first encounter?": "Что можно положить на стол для первой встречи?",
  "Where does your hand hesitate? Try that movement slowly.": "На каком движении рука запинается? Попробуйте его медленно.",
  "What would let you put the work down for tonight?": "Что позволит отложить работу до завтра?",
  "Meet and Return": "Встречаться и возвращаться",
  "Who might want to see this? Ask before handing it over.": "Кому, возможно, захочется это увидеть? Сначала спросите.",
  "What surprised you in the answer?": "Что удивило вас в ответе?",
  "What did the material teach you that the plan could not?": "Чему материал научил вас сверх того, что было в плане?",
  "Which part would you like to change, and which part can stay strange?": "Что хочется изменить, а что может остаться странным?",
  "What has come back: a question, a useful thing, a laugh, a need to repair?": "Что вернулось: вопрос, полезная вещь, смех, необходимость что-то исправить?",
  "Who needs an answer from you now?": "Кому сейчас нужен ваш ответ?",
  "Land": "Приземляться",
  "What remains different after the materials are put away?": "Что осталось другим после того, как материалы убраны?",
  "What ordinary act of care is waiting here?": "Какое обычное дело заботы ждёт рядом?",
  "Where did the Wind help, and where did you turn away from it?": "Где Ветер помог, а где вы отвернули от него?",
  "Which edge of your old map can you see now?": "Какой край старой карты теперь виден?",
  "What can remain unfinished without keeping you awake?": "Что может остаться незавершённым и при этом дать вам спокойно спать?",
  "Which image from these pages would you carry into tomorrow?": "Какой образ с этих страниц вы взяли бы в завтрашний день?",
  "Care, income, health, and obligations are real conditions. Naming them does not make an unjust arrangement acceptable.": "Забота, доход, здоровье и обязательства — реальные условия. Назвать их не значит согласиться с несправедливым устройством жизни.",
  "Changes that affect other people need consent, conversation, and attention to consequences. Where power makes conversation unsafe, seek appropriate outside help.": "Перемены, затрагивающие других, требуют согласия, разговора и внимания к последствиям. Если из-за неравенства власти разговор опасен, нужна подходящая помощь со стороны.",
  "These pages offer reflection, not diagnosis, treatment, or a promise about your future.": "Эти страницы предлагают размышление, а не диагноз, лечение или обещание будущего.",
  "Begin where life is already happening.": "Начинать там, где жизнь уже происходит.",
  "Let what you make return to it, carrying whatever the encounter has taught you.": "Возвращать в неё сделанное — вместе с тем, чему научила встреча.",
  "Turn one observation into a possible Call or honest non-answer.": "Превратите одно наблюдение в возможный Зов или честный отказ отвечать.",
  "Borrowed Map, Living Compass": "Чужая карта, живой Компас",
  "Choose the present place of one inherited route.": "Определите нынешнее место одного унаследованного маршрута.",
  "Template Escape": "Выход из шаблона",
  "Try one reversible variation without worshipping novelty.": "Попробуйте одну обратимую вариацию, не поклоняясь новизне.",
  "Flight Log": "Запись о Полёте",
  "Remember one complete or incomplete cycle without tracking a life.": "Запомните один полный или незавершённый цикл, не превращая жизнь в трекер.",
  "Meet an effect through learning, repair, privacy, value, or ending.": "Ответьте на последствие уроком, исправлением, приватностью, ценностью или завершением.",
  "Close or pause without debt to continue.": "Закройте или поставьте на паузу без долга продолжать.",
  "Choose a bounded role for AI and review adoption.": "Выберите ограниченную роль ИИ и проверьте, что именно было принято.",
  "Carry the framework into unequal adult responsibility with a child.": "Перенесите рамку в отношения, где ответственность взрослого и ребёнка неравна.",
  "Read the twelve governing articles.": "Прочитайте двенадцать основных статей.",
  "When the answer arrives first": "Когда ответ приходит первым",
  "A difficult letter comes back from the machine clear, graceful, and certain. You read it twice. It says more than you meant.": "Трудное письмо возвращается из машины ясным, красивым и уверенным. Вы читаете его дважды. Оно говорит больше, чем вы собирались сказать.",
  "Wind can give a thought reach. Its fluency can also carry a promise you never made.": "Ветер может дать мысли размах. Вместе с гладкой фразой он может принести обещание, которого вы не давали.",
  "Before sending, there is still a moment to hear your own uncertainty.": "Перед отправкой ещё есть мгновение, чтобы услышать собственную неуверенность.",
  "What in this answer can you stand behind when another person reads it?": "За что в этом ответе вы готовы отвечать, когда его прочитает другой человек?",
  "A human-first relationship with power": "Как обращаться с новой силой",
  "Wind changes movement; it does not choose a destination": "Ветер меняет движение, но не выбирает пункт назначения",
  "AI can change speed, options, resistance, and reach without gaining authority over purpose or consequence.": "ИИ меняет скорость, количество вариантов, сопротивление и дальность. От этого он не получает власти над целью или последствиями.",
  "Perhaps the tool found the sentence you had been reaching for. Perhaps it quietly supplied a feeling you do not have. Both can happen in the same paragraph. The work is to recognise the difference.": "Возможно, инструмент нашёл фразу, которую вы долго искали. Возможно, незаметно добавил чувство, которого у вас нет. И то и другое может произойти в одном абзаце. Предстоит различить их.",
  "Wind is powerful and uneven: some routes become easy to see, others disappear in its wake. Compass stays with the people who will live with the choice.": "Ветер силён и неровен: одни маршруты становятся заметными, другие исчезают за ними. Компас остаётся у людей, которым жить с этим выбором.",
  "Do not delegate the governing decisions": "Не отдавать решения, которые задают курс",
  "The human assignments": "Что остаётся за человеком",
  "AI may contribute material, critique, and craft; it does not receive authority over dignity, purpose, consent, or Return.": "ИИ может дать материал, критику или техническую помощь. Он не получает права решать вопросы достоинства, цели, согласия и Возвращения.",
  "Generation is not adoption. Sending the letter means choosing its words and promises. You can keep a phrase, change another, check a claim, or leave the draft unsent.": "Сгенерировать — ещё не значит принять. Отправляя письмо, вы выбираете его слова и обещания. Одну фразу можно оставить, другую изменить, утверждение проверить, а черновик пока не отправлять.",
  "Consent": "Согласие",
  "A simulation cannot consent for a maker, collaborator, child, audience, or represented person.": "Симуляция не может дать согласие за автора, соавтора, ребёнка, аудиторию или изображённого человека.",
  "Generated signs of attention do not replace noticing, listening, remaining reachable, and responding.": "Сгенерированные признаки внимания не заменяют способность заметить, выслушать, оставаться доступным и ответить.",
  "Compass": "Компас",
  "AI can supply arguments; values, limits, affected relations, revision, and choice remain human.": "ИИ может предложить аргументы. Ценности, границы, затронутые отношения, пересмотр и выбор остаются человеческими.",
  "Responsibility and Return": "Ответственность и Возвращение",
  "The people or institutions that adopt and act remain answerable for effects.": "Люди и организации, которые приняли форму и действуют через неё, продолжают отвечать за последствия.",
  "One role at a time": "По одной роли за раз",
  "Six roles for Wind": "Шесть ролей Ветра",
  "Naming one bounded role makes the intended relationship visible enough to inspect and reset.": "Одна названная и ограниченная роль делает отношения с инструментом достаточно ясными, чтобы их проверить и при необходимости начать заново.",
  "Mirror, Generator, Interlocutor, Critic, Craft aid, and Simulator are contributions, not hidden pilots. If the system begins choosing purpose, criteria, audience, form, and success at once, stop and return those decisions to Compass.": "Зеркало, Генератор, Собеседник, Критик, Помощник в ремесле и Симулятор — способы помочь, а не скрытые пилоты. Если система одновременно выбирает цель, критерии, аудиторию, форму и меру успеха, стоит остановиться и вернуть эти решения Компасу.",
  "Wind can enter; it is never an eighth stage": "Ветер может появиться на любом этапе, но не становится восьмым",
  "AI through the Flight cycle": "ИИ внутри цикла Полёта",
  "The letter leaves the screen and enters a relationship.": "Письмо выходит с экрана и попадает в отношения.",
  "The recipient may notice the sentence you almost removed. They may answer a day later, or ask something no rehearsal predicted. That reply belongs to the encounter. No generated audience can supply it in advance.": "Адресат может заметить фразу, которую вы едва не убрали. Ответить через день или спросить о том, чего не предсказала ни одна репетиция. Этот ответ принадлежит встрече. Сгенерированная аудитория не может дать его заранее.",
  "Return begins with attending to what actually came back, including silence or a promise that now needs keeping.": "Возвращение начинается с внимания к тому, что действительно пришло в ответ: иногда это тишина, иногда обещание, которое теперь нужно выполнить.",
  "Where the governing decisions live": "Где остаются решения, задающие курс",
  "Human-first does not mean opening the tool last": "Человек может начать с ИИ и всё равно остаться первым",
  "A process may begin with an AI draft and use extensive assistance while remaining human-first.": "Работа может начаться с черновика ИИ и широко использовать его помощь, не отдавая ему авторство курса.",
  "An AI draft can be the beginning of the work. The important question is whether you can recognise and explain what you choose to keep. A page made with extensive help can carry a considered decision; a sentence typed by hand can repeat someone else’s unexamined answer.": "Черновик ИИ может стать началом работы. Важно, узнаёте ли вы и можете ли объяснить то, что решили оставить. Страница, сделанная с большой помощью, способна нести обдуманное решение; фраза, набранная вручную, может повторять чужой ответ, о котором никто не задумался.",
  "Criteria": "Критерии",
  "People name or negotiate criteria and affected relationships.": "Люди называют или обсуждают критерии и затронутые отношения.",
  "Drift imports criteria from defaults, popularity, or confidence.": "При дрейфе критерии незаметно приходят из настроек по умолчанию, популярности или уверенного тона.",
  "Options": "Варианты",
  "Generated routes remain candidates alongside refusal and delay.": "Сгенерированные маршруты остаются кандидатами наряду с отказом и отсрочкой.",
  "Drift treats the visible option set as the boundary of imagination.": "При дрейфе видимый набор вариантов принимают за границу воображения.",
  "Making": "Дело",
  "The adopter understands enough to select, alter, explain, and verify the form.": "Принимающий понимает форму достаточно, чтобы выбрать, изменить, объяснить и проверить её.",
  "Drift accepts polish because it feels difficult to challenge.": "При дрейфе гладкий ответ принимают лишь потому, что с ним трудно спорить.",
  "A voluntary practice": "Добровольная практика",
  "Give AI a visible role before fluency becomes direction.": "Дать ИИ видимую роль до того, как гладкость ответа начнёт задавать направление.",
  "A brief note can hold the question while you work. Give the tool one job, protect private material, and keep the answer small enough to examine. The note is useful for as long as it helps you see your decisions.": "Короткая заметка поможет удержать вопрос во время работы. Дайте инструменту одну задачу, сберегите личное и запросите ответ, который сможете рассмотреть. Заметка нужна, пока с ней лучше видны ваши решения.",
  "The question": "Вопрос",
  "What are you trying to say or make, and who may be affected?": "Что вы пытаетесь сказать или сделать и кого это затронет?",
  "The help": "Помощь",
  "What one task can the tool help with? Which decisions stay with you?": "В какой одной задаче поможет инструмент? Какие решения останутся за вами?",
  "The material": "Материал",
  "Use the minimum necessary context; prefer generic, fictionalised, or person-created material.": "Дайте минимум необходимого контекста. Предпочитайте обобщённый, вымышленный или созданный самим человеком материал.",
  "The answer": "Ответ",
  "What will you accept, change, reject, or verify before using it?": "Что вы примете, измените, отвергнете или проверите, прежде чем использовать ответ?",
  "The hardest case is an attractive route": "Самый трудный случай — привлекательный маршрут",
  "Recover direction from a polished proposal": "Вернуть направление после гладкого предложения",
  "An appealing AI proposal is a candidate map, not a discovered purpose.": "Привлекательное предложение ИИ — одна из возможных карт, а не обнаруженная жизненная цель.",
  "You asked about a small neighbourhood problem. The reply offers a name, a business, a launch plan. It is easy to begin polishing that plan and forget the person whose difficulty first caught your attention. Put the original question beside the proposal. See whether they still belong together.": "Вы спросили о небольшой проблеме во дворе. В ответ пришли название, бизнес и план запуска. Легко начать улучшать этот план и забыть человека, чья трудность сначала привлекла внимание. Положите исходный вопрос рядом с предложением. Посмотрите, относятся ли они ещё друг к другу.",
  "Keep the child out of the instrument panel": "Не превращать ребёнка в данные для панели управления",
  "Families use AI without profiling a child": "Семья может пользоваться ИИ, не составляя профиль ребёнка",
  "The adult keeps safety, privacy, time, limits, and care; the child keeps authorship wherever a real choice exists.": "Взрослый удерживает безопасность, приватность, время, границы и заботу. Там, где выбор реален, авторство остаётся у ребёнка.",
  "Do not ask AI whether a child is creative, gifted, lazy, resistant, mature, diagnosable, risky, or destined for a path. Do not enter private child material merely to obtain a more personal answer.": "Не нужно спрашивать у ИИ, творческий ли ребёнок, одарённый, ленивый, упрямый, зрелый, «диагностируемый», опасный или предназначенный для какого-то пути. Личные материалы ребёнка нельзя отдавать системе только ради более персонального ответа.",
  "Legitimate roles include open-ended material ideas, simpler instructions, several demonstrations, reviewed translation of child-authored text, or questions about conditions the adult controls.": "Уместные роли проще: предложить разные материалы без готового результата, упростить инструкцию, показать несколько способов, помочь с проверяемым переводом детского текста или задать взрослому вопросы об условиях, которыми он управляет.",
  "Failures belong to an encounter, not a person": "Сбой относится к встрече, а не к человеку",
  "Where the course begins to shift": "Где начинает меняться курс",
  "A familiar failure can become easier to notice the next time.": "Знакомый сбой бывает проще заметить в следующий раз.",
  "The repair is not trust yourself instead. Compass may require evidence, collaborators, affected people, expertise, traditions, or rules.": "Исправление не сводится к совету «просто доверься себе». Компасу могут понадобиться факты, соавторы, затронутые люди, профессиональное знание, традиция или правила.",
  "An unexamined output is published": "Непроверенный ответ публикуют",
  "The publisher cannot explain or defend the polished form.": "Публикующий не может объяснить или защитить гладкую форму.",
  "Pause; run Accept, Change, Reject, Verify; check sources and relationships; revise, attribute, or do not publish.": "Остановитесь. Пройдите решения «принять, изменить, отвергнуть, проверить», сверьте источники и отношения. Исправьте, укажите происхождение или не публикуйте.",
  "Options become an avalanche": "Варианты превращаются в лавину",
  "More generation feels productive while no choice is made.": "Новые варианты создают ощущение работы, хотя выбор так и не сделан.",
  "Stop, restate the Call, choose two criteria, keep a small set, or return to Ground.": "Остановитесь, верните Зов, выберите два критерия, оставьте небольшой набор — или вернитесь к Земле.",
  "The critic becomes a judge": "Критик становится судьёй",
  "Feedback is read as a verdict on ability or worth.": "Обратную связь принимают за приговор способностям или ценности человека.",
  "Separate fact, ethics, craft, and taste; choose legitimate criteria and reject the rank.": "Разделите факт, этику, ремесло и вкус. Выберите уместные критерии и отвергните ранг.",
  "Speed outruns consent": "Скорость обгоняет согласие",
  "Material is shared or transformed before boundaries are checked.": "Материал передают или изменяют раньше, чем проверяют границы.",
  "Stop distribution, identify affected interests, seek real consent where required, limit use, and repair effects.": "Остановите распространение, определите затронутые интересы, получите реальное согласие там, где оно нужно, ограничьте использование и исправьте последствия.",
  "Completion replaces learning": "Готовый результат заменяет обучение",
  "A craft aid performs the operation the person intended to practise.": "Помощник выполняет операцию, которую человек хотел освоить сам.",
  "Choose learning or delivery consciously, then narrow assistance or change the aim.": "Осознанно выберите обучение или готовый результат, затем сузьте помощь или измените цель.",
  "One route becomes invisible normality": "Один маршрут становится невидимой нормой",
  "Repeated outputs narrow style, assumptions, or represented lives.": "Повторяющиеся ответы сужают стиль, предположения или представленные способы жизни.",
  "Name the pattern, vary sources and constraints, invite affected perspectives, and keep rejection open.": "Назовите шаблон, меняйте источники и ограничения, приглашайте затронутые точки зрения и оставляйте право отказаться.",
  "“The AI said so”": "«Так сказал ИИ»",
  "The AI said so is used after harm.": "После причинённого вреда звучит оправдание: «так сказал ИИ».",
  "Name who chose, approved, and acted; meet the effect; repair the form or process.": "Назовите, кто выбрал, утвердил и действовал. Ответьте на последствие и исправьте форму или процесс.",
  "Generation is not adoption": "Генерация — ещё не принятие",
  "Adopt and attribute in proportion to consequence": "Принимать и указывать источник соразмерно последствиям",
  "Attribution says where material came from; adoption says who chose to use it and remains answerable.": "Указание источника отвечает на вопрос, откуда взялся материал. Принятие — кто решил его использовать и продолжает отвечать за последствия.",
  "For work you share, explain the relevant help you used, check what others will rely on, and name who can respond if something is wrong. Public and professional settings may require more: permissions, sources, credit, and the rules of the place where the work will appear.": "В работе, которой вы делитесь, назовите существенную помощь, проверьте то, на что будут опираться другие, и определите, кто ответит, если обнаружится ошибка. Для публичной и профессиональной работы могут понадобиться разрешения, источники, указание авторства и соблюдение правил места, где она появится.",
  "No race for human superiority": "Не нужно соревноваться с машиной за превосходство",
  "Choose assistance by meaning, learning, access, and responsibility": "Выбирать помощь по смыслу, обучению, доступности и ответственности",
  "Craft matters because it helps intention meet material honestly, not because it protects a competitive human advantage.": "Ремесло важно потому, что помогает замыслу честно встретиться с материалом, а не потому, что охраняет конкурентное преимущество человека.",
  "Sometimes assistance opens a door: a translation reaches someone you could not address; a prototype lets you try an idea while it is still vivid. Sometimes you want to learn the slow operation yourself. Its resistance is part of what you came for.": "Иногда помощь открывает дверь: перевод доходит до человека, к которому вы иначе не смогли бы обратиться; прототип позволяет попробовать ещё живую идею. Иногда хочется самому освоить медленную операцию. Её сопротивление — часть того, ради чего вы пришли.",
  "Choose the help that serves this encounter. Leave room to discover that you need a different kind.": "Выбирайте помощь для этой встречи. Оставляйте место открытию, что нужна другая.",
  "The Adoption Test": "Проверка принятия",
  "Check whether an AI-assisted form is ready to enter a consequential setting.": "Проверьте, готова ли форма с участием ИИ войти в ситуацию, где будут последствия.",
  "Answer: What role did AI play? What did it contribute? What was accepted, changed, rejected, or verified? Who and what remain relevant? Who responds if it is wrong?": "Ответьте: какую роль играл ИИ? Что он добавил? Что было принято, изменено, отвергнуто или проверено? Чьи интересы и какие факты всё ещё важны? Кто ответит, если форма окажется неверной?",
  "The adopter can answer—or reduces the stakes, seeks review, revises, or does not adopt yet.": "Принимающий может ответить — либо снижает ставки, ищет проверку, исправляет форму или пока её не принимает.",
  "Attribution does not transfer responsibility, and disclosure does not make unsafe use safe.": "Указание источника не передаёт ответственность, а раскрытие участия ИИ не делает опасное применение безопасным.",
  "Assistance without self-erasure": "Помощь без стирания себя",
  "The letter is ready. One sentence remains: “I know exactly how you feel.” The writer stops over it.": "Письмо готово. В нём осталась фраза: «Я точно знаю, что ты чувствуешь». Автор останавливается на ней.",
  "Send it because it sounds competent—or delete it because any assistance would make the letter false.": "Отправить, потому что звучит убедительно, — или удалить, потому что любая помощь якобы делает письмо фальшивым.",
  "The sentence becomes: “I keep wondering how this has been for you.” The letter is less certain now. It leaves room for an answer the writer does not yet know. Before sending, the writer checks the other claims and promises too.": "Вместо неё появляется: «Я всё думаю, каково тебе сейчас». В письме стало меньше уверенности. Появилось место ответу, которого автор ещё не знает. Перед отправкой он проверяет и остальные утверждения и обещания.",
  "Authorship is not a percentage of human-made words. It is a form the person can recognise, explain, and answer for.": "Авторство не измеряется процентом слов, написанных человеком. Это форма, которую он узнаёт как свою, может объяснить и за которую готов отвечать.",
  "Consent comes from the people involved. A simulation cannot grant it or establish what happened in the world.": "Согласие дают затронутые люди. Симуляция не может дать его за них или установить, что произошло в мире.",
  "Keep private material out of unnecessary requests. Children must not be profiled, diagnosed, or ranked by the system.": "Берегите личные материалы от лишней передачи. Система не должна составлять профили детей, ставить им диагнозы или ранжировать их.",
  "Those who choose and use an answer remain responsible for its consequences. Check claims, rights, and professional requirements before others rely on them.": "Те, кто выбрал и использовал ответ, отвечают за последствия. Проверяйте утверждения, права и профессиональные требования до того, как на них положатся другие.",
  "Wind is a metaphor for a relationship with a tool, not a guarantee of any system’s abilities. Human help and a route without AI remain available.": "Ветер — метафора отношений с инструментом, а не гарантия возможностей системы. Помощь человека и путь без ИИ остаются доступными.",
  "Let the Wind widen what can be made.": "Пусть Ветер расширяет то, что можно сделать.",
  "Keep listening for the question beneath the answer.": "Продолжать слышать вопрос под готовым ответом.",
  "Create a bounded Wind agreement and human adoption note.": "Составьте ограниченное соглашение о Ветре и отметьте человеческие решения.",
  "Apply the family boundary while retaining unequal adult responsibility.": "Примените семейную границу, сохраняя большую ответственность взрослого.",
  "Return the tool boundary to a present-life human direction.": "Верните границу инструмента в направление нынешней человеческой жизни.",
  "Meet the effects of an adopted form in a real relationship.": "Встретьтесь с последствиями принятой формы в реальных отношениях.",
  "Stop the system and close the cycle without promising another.": "Остановите систему и закройте цикл, не обещая следующий.",
  "See why Wind remains one part of a larger ethical world.": "Посмотрите, почему Ветер остаётся лишь частью более широкого этического мира.",
  "Mirror": "Зеркало",
  "Reflects a draft, summary, tension, or repeated pattern back to the maker.": "Возвращает автору его черновик, главную мысль, внутреннее противоречие или повторяющийся ход.",
  "A tidy reflection can erase ambiguity or make one interpretation feel definitive.": "Слишком гладкое отражение стирает важную неясность и выдаёт одну трактовку за окончательную.",
  "Decide whether the reflection is recognisable, what it leaves out, and whether it changes the Call.": "Сам человек решает, узнаёт ли он себя в этом отражении, чего там не хватает и не подменило ли оно исходный Зов.",
  "Reflect my current position in no more than five points. Mark interpretations you add. Do not name my true purpose. End with one question I may decline.": "Отразите мою нынешнюю позицию максимум в пяти пунктах. Отдельно пометьте свои трактовки. Не объявляйте, в чём моя истинная цель. В конце задайте один вопрос — я могу на него не отвечать.",
  "Generator": "Генератор",
  "Produces materially different options, examples, questions, structures, or forms.": "Предлагает действительно разные варианты, примеры, вопросы, структуры или формы.",
  "Abundance can replace choosing, while familiar patterns quietly define the option set.": "Изобилие вариантов легко подменяет выбор, а привычные шаблоны незаметно очерчивают границы возможного.",
  "Choose which options deserve attention, what criteria matter, and whether to choose any.": "Человек решает, какие варианты вообще стоит рассматривать, по каким критериям и нужно ли выбирать сейчас.",
  "Offer five materially different responses to this Call. State each assumption. Include doing nothing now. Do not rank them until I provide criteria.": "Предложите пять существенно разных ответов на этот Зов. Для каждого назовите исходные предположения. Включите вариант ничего пока не делать. Не ранжируйте ответы, пока я не задам критерии.",
  "Interlocutor": "Собеседник",
  "Asks questions, rehearses a conversation, or helps articulate an unfinished thought.": "Задаёт вопросы, помогает подготовиться к разговору или выразить ещё не сложившуюся мысль.",
  "Dialogue can become an agreeable loop or give fluency the aura of understanding.": "Диалог может замкнуться в приятном согласии, а складная речь — создать иллюзию понимания.",
  "Decide which question is real, when another human is needed, and when to end the exchange.": "Человек решает, какой вопрос здесь настоящий, когда нужен живой собеседник и когда разговор с системой пора закончить.",
  "Ask one clarifying question at a time. Separate what I observed, assumed, and care about. Do not turn my answer into a diagnosis or mission.": "Задавайте по одному уточняющему вопросу. Разделяйте мои наблюдения, предположения и то, что мне небезразлично. Не превращайте ответы в диагноз или жизненную миссию.",
  "Critic": "Критик",
  "Tests assumptions, identifies gaps, checks stated criteria, and offers counterarguments.": "Проверяет предположения, находит пробелы, сверяется с заданными критериями и приводит контраргументы.",
  "Confident criticism can become a moral verdict, imported taste, or endless revision.": "Уверенный тон критика легко принять за моральный приговор, чужой вкус — за правило, а правки сделать бесконечными.",
  "Choose legitimate criteria, decide what criticism to adopt, and decide when the form is ready enough.": "Автор выбирает уместные критерии, принимает или отвергает замечания и сам решает, когда работа достаточно готова.",
  "Test this form against my stated criteria. Separate factual gaps, ethical concerns, craft choices, and taste. Suggest repairs without scoring me or the work.": "Проверьте эту форму по моим критериям. Разделите фактические пробелы, этические вопросы, ремесленные решения и вкус. Предложите, что можно поправить, но не выставляйте оценку ни мне, ни работе.",
  "Craft aid": "Помощник в ремесле",
  "Helps edit, translate, restructure, format, prototype, calculate, or execute a chosen technique.": "Помогает редактировать, переводить, перестраивать, верстать, прототипировать, считать или выполнять выбранный технический приём.",
  "Friction can vanish before the maker learns which part of the craft matters to this attempt.": "Система может убрать трудность раньше, чем автор поймёт, чему именно здесь стоило научиться.",
  "Keep the intended effect, acceptable method, verification standard, and final adoption human.": "Замысел, допустимый способ работы, способ проверки и окончательное решение остаются у человека.",
  "Help with this bounded craft operation. Preserve the decisions I name. Flag changes to meaning, consent, attribution, or audience.": "Помогите только с этой ограниченной операцией. Сохраните решения, которые я перечислю. Отмечайте всё, что меняет смысл, согласие, авторство или адресата.",
  "Simulator": "Симулятор",
  "Generates plausible questions, edge cases, scenarios, or audience reactions before real contact.": "Предлагает возможные вопросы, пограничные случаи, сценарии или реакции аудитории до встречи с реальностью.",
  "A plausible simulation can be mistaken for evidence, consent, lived experience, or feedback.": "Правдоподобный сценарий легко спутать с фактом, согласием, живым опытом или настоящей обратной связью.",
  "Name what still requires reality and whose real voice must still be heard.": "Нужно назвать, что ещё предстоит проверить в реальности и чей живой голос всё ещё необходимо услышать.",
  "Generate plausible reactions from the stated context. Label them hypotheses, not evidence. Name what only a real person, source, or trial can answer.": "Предложите возможные реакции в заданном контексте и пометьте их как гипотезы, а не факты. Отдельно назовите вопросы, на которые ответит только реальный человек, источник или проверка."
};

const structuralKeys = new Set([
  "id",
  "href",
  "route",
  "kind",
  "atlasExperienceId",
]);

function localizeDeep<T>(value: T, key = ""): T {
  if (Array.isArray(value)) {
    return value.map((item) => localizeDeep(item, key)) as T;
  }

  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([childKey, childValue]) => [
        childKey,
        structuralKeys.has(childKey)
          ? childValue
          : localizeDeep(childValue, childKey),
      ]),
    ) as T;
  }

  if (typeof value === "string" && !structuralKeys.has(key)) {
    return (readerTextRu[value] ?? value) as T;
  }

  return value;
}

export const windRolesRu = localizeDeep(windRoles);

export const pathwaysRu = localizeDeep(pathways) as unknown as Record<
  PathwayId,
  PathwayDefinition
>;

export const pathwayListRu = [
  pathwaysRu.parent,
  pathwaysRu.adult,
  pathwaysRu.ai,
] as const;

export function getPathwayRu(pathwayId: PathwayId): PathwayDefinition {
  return pathwaysRu[pathwayId];
}
